# Generated by Django 5.0.3 on 2024-03-20 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240320_0849'),
    ]

    operations = [
    ]
