# Generated by Django 5.0.3 on 2024-03-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='auther',
            new_name='author',
        ),
    ]
